# Generated by Django 5.0.4 on 2024-04-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='fullname',
            field=models.TextField(verbose_name='фио'),
        ),
    ]
