# Generated by Django 5.0.4 on 2024-04-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule', '0004_mailingattempt_mailing_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='frequency',
            field=models.CharField(choices=[('Ежедневно', 'раз в день'), ('Еженедельно', 'раз в неделю'), ('Ежемесячно', 'раз в месяц')], max_length=300),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status_of_newsletter',
            field=models.CharField(choices=[('Создать', 'Создана'), ('Запустить', 'Отправлено'), ('Завершить', 'Завершена')], max_length=150, verbose_name='статус рассылки'),
        ),
    ]
