# Generated by Django 5.0.4 on 2024-05-12 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shedule', '0005_alter_newsletter_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='clients',
            field=models.ManyToManyField(to='shedule.client', verbose_name='Клиенты'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='frequency',
            field=models.CharField(choices=[('Ежедневно', 'раз в день'), ('Еженедельно', 'раз в неделю'), ('Ежемесячно', 'раз в месяц')], max_length=300, verbose_name='Частота отправки'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shedule.textfornewsletter', verbose_name='Сообщение для отправки'),
        ),
    ]
